version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_SLAVE_AGENT_PORT}:5000"
    volumes:
      - "${JENKINS_HOME}:/var/jenkins_home:rw"
    networks:
      - default
networks:
  default:
